### PR TITLE
set include, includeexpr and path

### PR DESCRIPTION
**Pull request by coot**
This enables:
* gf normal command over module name in the import section
* ]i, ]I normal commands
* :find command to navigate through all the source files

### CODE REVIEW

**Comment by raichoo** [comment]
I'm currently not actively working on this so maybe @arthur-xavier can also have a look.

**Comment by arthur-xavier** [comment]
These are some nice improvements there! Thanks a lot! `]i` and `]I` are fantastic!

Tested it all and everything works fine as of `vim-8.0.525` and `nvim-0.2.1-359`. It's a shame, however, that imports under `bower_components` could only be located with `gf` after I removed `bower_components` from my `wildignore` list.

Do you know perhaps any solution for that?

**Comment by coot** [comment]
vim normal mode commands are are linked to command, I think that `gf` is sharing code with `find`. But I couldn't reproduce your issue even with `se wig+=*.purs` neither with `se wig=bower_components/**` (and `set acd=0`). 

What you could do is to map gf to a function which temporarily changes `wildignore`:
```
fun! Gf()
  let wig = &wig
  set wig -= bower_components
  normal "gf"
  let &wig = wig
endfun
```

**Comment by arthur-xavier** [comment]
That's a witty trick! Works great! Unfortunately I had to use it as `<leader>gf`. Otherwise it would infinitely recurse.

**Pull request merged**
